name: Postman api tests

# Run Postman's headless collection runner alias newman
# Only trigger, when the workflow described in maven-build.yml succeeded
on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    services:
      rest-api:
        image: siincy/wpm_wise2122_devops_spring_petclinic_deployment:rest
        ports:
           - 9966:9966
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Test_Postman
        uses: matt-ball/newman-action@master
        with:
         collection: postman_collection.json
