name: Postman api tests

# Run Postman's headless collection runner alias newman
# Only trigger, when the workflow described in maven-build.yml succeeded
on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}   
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
          
      - name: grant access
        run: sudo chmod +x mvnw
      
      - name: Sleep for 90 seconds
        uses: jakejarvis/wait-action@master
        with:
            time: '90s'
      
      - name: Start project
        run: nohup ./mvnw spring-boot:run &
        
      - name: Test_Postman
        uses: matt-ball/newman-action@master
        with:        
          collection: postman_collection.json
